### ISSUE TITLE
Limit number of days in WporgClient::getPluginDownloads to 730

### ISSUE THREAD

**Issue by engelen** [Rarst/wporg-client#2]
The WordPress API will use the default limit (180 days) if the limit passed to in the API call exceeds 731. The `getPluginDownloads` method of WporgClient should probably attend to this by limiting the number of days to 730 and mentioning it in the method's block-documentation.

**Comment by Rarst** [comment]
Is this documented something (so it can be linked to) or just empirically determined?

**Comment by engelen** [comment]
It's not documented anywhere as far as I know, but I've determined it empirically with quite some certainty, and the fact that it's 2*365 adds to my suspicion that it is no coincidence :-). Anyway, saw the commit, nice.
