### ISSUE TITLE
Update getPluginsInfo to version 1.1

### ISSUE THREAD

**Issue by swissspidy** [Rarst/wporg-client#5]
Is there any reason why this operation defaults to version `1.0`?

Version 1.1 returns JSON by default and is easier to handle. I'm not that familiar with Guzzle, but it might be as easy as using `'responseModel' => 'json'` instead of `'responseModel' => 'serialized'`

Version 1.1 contains additional info like the `active_installs` field, which version 1.0 doesn't seem to support at all.

**Comment by Rarst** [comment]
Mmm... because I have no remote idea at which point 1.1 was made available and it's not documented (well, none of it is really) ? :)

I'll look into updating, thank you for bringing it up!

**Comment by Rarst** [comment]
Fixed in 0.5

Note that both API versions do seem to support `active_installs`, but you need to proactively request it in fields. APIs seems to omit it, unless explicitly asked for.
