### ISSUE TITLE
PHP 8.1 Compatibility

### ISSUE THREAD

**Issue by Rahe** [Rarst/wporg-client#6]
Hello,

On PHP8.1 when calling getUpdates I have several PHP "Deprecated" errors because of guzzle 6.5 not compatible with PHP8.1.

Is an upgrade possible ? Guzzle 7 seems to with PHP versions  >=7.2.5,<8.2.

Thank you :)
Nicolas,

**Comment by Rarst** [comment]
Hard to say right away, it would be more about Guzzle Services, which had seen a lot more sporadic development than Guzzle itself and I am not up to date on the state and compatibility of it.

**Comment by Rarst** [comment]
I refreshed dependencies and _surprisingly_ it seems to work. I don't have this in active use anywhere, so if you could please try that, I will tag a release. :)

**Comment by Rahe** [comment]
Hello,

Thank you very much for the update, this is working perfectly with the current master state.

Nicolas

**Comment by Rarst** [comment]
Cheers, released on 0.6
